{
  message: 'Erro em processamento do job SendEmail (ID: 1)',
  error: 'Configuração de e-mail não encontrada.',
  stack: 'Error: Configuração de e-mail não encontrada.\n' +
    '    at createTransporter (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\providers\\mail.provider.js:14:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendEmail.js:21:46)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-29T15:34:19.947Z'
}
{
  error: Error: Configuração de e-mail não encontrada.
      at createTransporter (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\providers\mail.provider.js:14:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendEmail.js:21:46)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendEmail] Job 1 falhou. Erro: Configuração de e-mail não encontrada.',
  timestamp: '2025-09-29T15:34:20.174Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 1)',
  error: 'Configuração de e-mail não encontrada.',
  stack: 'Error: Configuração de e-mail não encontrada.\n' +
    '    at createTransporter (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\providers\\mail.provider.js:14:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendEmail.js:21:46)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-29T15:34:21.023Z'
}
{
  error: Error: Configuração de e-mail não encontrada.
      at createTransporter (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\providers\mail.provider.js:14:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendEmail.js:21:46)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendEmail] Job 1 falhou. Erro: Configuração de e-mail não encontrada.',
  timestamp: '2025-09-29T15:34:21.237Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 1)',
  error: 'Configuração de e-mail não encontrada.',
  stack: 'Error: Configuração de e-mail não encontrada.\n' +
    '    at createTransporter (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\providers\\mail.provider.js:14:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendEmail.js:21:46)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-29T15:34:22.105Z'
}
{
  error: Error: Configuração de e-mail não encontrada.
      at createTransporter (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\providers\mail.provider.js:14:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendEmail.js:21:46)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendEmail] Job 1 falhou. Erro: Configuração de e-mail não encontrada.',
  timestamp: '2025-09-29T15:34:22.319Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 1)',
  error: 'Configuração de e-mail não encontrada.',
  stack: 'Error: Configuração de e-mail não encontrada.\n' +
    '    at createTransporter (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\providers\\mail.provider.js:14:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendEmail.js:21:46)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-29T15:34:23.090Z'
}
{
  error: Error: Configuração de e-mail não encontrada.
      at createTransporter (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\providers\mail.provider.js:14:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendEmail.js:21:46)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendEmail] Job 1 falhou. Erro: Configuração de e-mail não encontrada.',
  timestamp: '2025-09-29T15:34:23.305Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 1)',
  error: 'Configuração de e-mail não encontrada.',
  stack: 'Error: Configuração de e-mail não encontrada.\n' +
    '    at createTransporter (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\providers\\mail.provider.js:14:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendEmail.js:21:46)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-29T15:34:23.765Z'
}
{
  error: Error: Configuração de e-mail não encontrada.
      at createTransporter (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\providers\mail.provider.js:14:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendEmail.js:21:46)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendEmail] Job 1 falhou. Erro: Configuração de e-mail não encontrada.',
  timestamp: '2025-09-29T15:34:23.989Z'
}
{
  message: 'Error send message api',
  error: TelegramError: 400: Bad Request: chat not found
      at Telegram.callApi (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\telegraf\lib\core\network\client.js:315:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:61:21)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24) {
    response: {
      ok: false,
      error_code: 400,
      description: 'Bad Request: chat not found'
    },
    on: {
      method: 'sendMessage',
      payload: {
        chat_id: '0',
        text: 'Olá,\n' +
          '\n' +
          'Seu chamado foi atualizado com as seguintes informações:\n' +
          '\n' +
          '🔹 ID do Chamado: 4\n' +
          '🔹 Assunto: Erros na nova versao a ser olhado\n' +
          '🔹 Técnico Responsável: Administrador Renato\n' +
          '\n' +
          'Erro 500 na rota https://fast.panelapps.site/email/send/4/close\n' +
          'Método da solicitação\n' +
          'POST\n' +
          '\n' +
          'Caso tenha alguma dúvida ou precise de mais informações, estamos à disposição.\n' +
          '\n' +
          'Atenciosamente,\n' +
          '[Nome da Equipe/Suporte]'
      }
    }
  },
  level: 'error',
  timestamp: '2025-09-29T15:45:00.719Z'
}
{
  message: 'Erro em processamento do job SendMessageChamado (ID: 1)',
  error: 'Error: 400: Bad Request: chat not found',
  stack: 'Error: Error: 400: Bad Request: chat not found\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendMessageChamado.js:89:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-29T15:45:00.728Z'
}
{
  error: Error: Error: 400: Bad Request: chat not found
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:89:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendMessageChamado] Job 1 falhou. Erro: Error: 400: Bad Request: chat not found',
  timestamp: '2025-09-29T15:45:00.953Z'
}
{
  message: 'Error send message api',
  error: TelegramError: 400: Bad Request: chat not found
      at Telegram.callApi (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\telegraf\lib\core\network\client.js:315:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:61:21)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24) {
    response: {
      ok: false,
      error_code: 400,
      description: 'Bad Request: chat not found'
    },
    on: {
      method: 'sendMessage',
      payload: {
        chat_id: '0',
        text: 'Olá,\n' +
          '\n' +
          'Seu chamado foi atualizado com as seguintes informações:\n' +
          '\n' +
          '🔹 ID do Chamado: 4\n' +
          '🔹 Assunto: Erros na nova versao a ser olhado\n' +
          '🔹 Técnico Responsável: Administrador Renato\n' +
          '\n' +
          'Erro 500 na rota https://fast.panelapps.site/email/send/4/close\n' +
          'Método da solicitação\n' +
          'POST\n' +
          '\n' +
          'Caso tenha alguma dúvida ou precise de mais informações, estamos à disposição.\n' +
          '\n' +
          'Atenciosamente,\n' +
          '[Nome da Equipe/Suporte]'
      }
    }
  },
  level: 'error',
  timestamp: '2025-09-29T15:45:02.960Z'
}
{
  message: 'Erro em processamento do job SendMessageChamado (ID: 1)',
  error: 'Error: 400: Bad Request: chat not found',
  stack: 'Error: Error: 400: Bad Request: chat not found\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendMessageChamado.js:89:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-29T15:45:02.961Z'
}
{
  error: Error: Error: 400: Bad Request: chat not found
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:89:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendMessageChamado] Job 1 falhou. Erro: Error: 400: Bad Request: chat not found',
  timestamp: '2025-09-29T15:45:03.184Z'
}
{
  message: 'Error send message api',
  error: TelegramError: 400: Bad Request: chat not found
      at Telegram.callApi (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\telegraf\lib\core\network\client.js:315:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:61:21)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24) {
    response: {
      ok: false,
      error_code: 400,
      description: 'Bad Request: chat not found'
    },
    on: {
      method: 'sendMessage',
      payload: {
        chat_id: '0',
        text: 'Olá,\n' +
          '\n' +
          'Seu chamado foi atualizado com as seguintes informações:\n' +
          '\n' +
          '🔹 ID do Chamado: 4\n' +
          '🔹 Assunto: Erros na nova versao a ser olhado\n' +
          '🔹 Técnico Responsável: Administrador Renato\n' +
          '\n' +
          'Erro 500 na rota https://fast.panelapps.site/email/send/4/close\n' +
          'Método da solicitação\n' +
          'POST\n' +
          '\n' +
          'Caso tenha alguma dúvida ou precise de mais informações, estamos à disposição.\n' +
          '\n' +
          'Atenciosamente,\n' +
          '[Nome da Equipe/Suporte]'
      }
    }
  },
  level: 'error',
  timestamp: '2025-09-29T15:45:05.294Z'
}
{
  message: 'Erro em processamento do job SendMessageChamado (ID: 1)',
  error: 'Error: 400: Bad Request: chat not found',
  stack: 'Error: Error: 400: Bad Request: chat not found\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendMessageChamado.js:89:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-29T15:45:05.295Z'
}
{
  error: Error: Error: 400: Bad Request: chat not found
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:89:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendMessageChamado] Job 1 falhou. Erro: Error: 400: Bad Request: chat not found',
  timestamp: '2025-09-29T15:45:05.519Z'
}
{
  message: 'Error send message api',
  error: TelegramError: 400: Bad Request: chat not found
      at Telegram.callApi (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\telegraf\lib\core\network\client.js:315:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:61:21)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24) {
    response: {
      ok: false,
      error_code: 400,
      description: 'Bad Request: chat not found'
    },
    on: {
      method: 'sendMessage',
      payload: {
        chat_id: '0',
        text: 'Olá,\n' +
          '\n' +
          'Seu chamado foi atualizado com as seguintes informações:\n' +
          '\n' +
          '🔹 ID do Chamado: 4\n' +
          '🔹 Assunto: Erros na nova versao a ser olhado\n' +
          '🔹 Técnico Responsável: Administrador Renato\n' +
          '\n' +
          'Erro 500 na rota https://fast.panelapps.site/email/send/4/close\n' +
          'Método da solicitação\n' +
          'POST\n' +
          '\n' +
          'Caso tenha alguma dúvida ou precise de mais informações, estamos à disposição.\n' +
          '\n' +
          'Atenciosamente,\n' +
          '[Nome da Equipe/Suporte]'
      }
    }
  },
  level: 'error',
  timestamp: '2025-09-29T15:45:07.672Z'
}
{
  message: 'Erro em processamento do job SendMessageChamado (ID: 1)',
  error: 'Error: 400: Bad Request: chat not found',
  stack: 'Error: Error: 400: Bad Request: chat not found\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendMessageChamado.js:89:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-29T15:45:07.673Z'
}
{
  error: Error: Error: 400: Bad Request: chat not found
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:89:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendMessageChamado] Job 1 falhou. Erro: Error: 400: Bad Request: chat not found',
  timestamp: '2025-09-29T15:45:07.896Z'
}
{
  message: 'Error send message api',
  error: TelegramError: 400: Bad Request: chat not found
      at Telegram.callApi (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\telegraf\lib\core\network\client.js:315:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:61:21)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24) {
    response: {
      ok: false,
      error_code: 400,
      description: 'Bad Request: chat not found'
    },
    on: {
      method: 'sendMessage',
      payload: {
        chat_id: '0',
        text: 'Olá,\n' +
          '\n' +
          'Seu chamado foi atualizado com as seguintes informações:\n' +
          '\n' +
          '🔹 ID do Chamado: 4\n' +
          '🔹 Assunto: Erros na nova versao a ser olhado\n' +
          '🔹 Técnico Responsável: Administrador Renato\n' +
          '\n' +
          'Erro 500 na rota https://fast.panelapps.site/email/send/4/close\n' +
          'Método da solicitação\n' +
          'POST\n' +
          '\n' +
          'Caso tenha alguma dúvida ou precise de mais informações, estamos à disposição.\n' +
          '\n' +
          'Atenciosamente,\n' +
          '[Nome da Equipe/Suporte]'
      }
    }
  },
  level: 'error',
  timestamp: '2025-09-29T15:45:09.798Z'
}
{
  message: 'Erro em processamento do job SendMessageChamado (ID: 1)',
  error: 'Error: 400: Bad Request: chat not found',
  stack: 'Error: Error: 400: Bad Request: chat not found\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendMessageChamado.js:89:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-29T15:45:09.799Z'
}
{
  error: Error: Error: 400: Bad Request: chat not found
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:89:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendMessageChamado] Job 1 falhou. Erro: Error: 400: Bad Request: chat not found',
  timestamp: '2025-09-29T15:45:10.025Z'
}
{
  message: 'Error send message api',
  error: TelegramError: 400: Bad Request: chat not found
      at Telegram.callApi (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\telegraf\lib\core\network\client.js:315:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:61:21)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24) {
    response: {
      ok: false,
      error_code: 400,
      description: 'Bad Request: chat not found'
    },
    on: {
      method: 'sendMessage',
      payload: {
        chat_id: '0',
        text: 'Olá,\n' +
          '\n' +
          'Seu chamado foi atualizado com as seguintes informações:\n' +
          '\n' +
          '🔹 ID do Chamado: 4\n' +
          '🔹 Assunto: Erros na nova versao a ser olhado\n' +
          '🔹 Técnico Responsável: Administrador Renato\n' +
          '\n' +
          'Erro 500 na rota https://fast.panelapps.site/email/send/4/close\n' +
          'Método da solicitação\n' +
          'POST\n' +
          '\n' +
          'Caso tenha alguma dúvida ou precise de mais informações, estamos à disposição.\n' +
          '\n' +
          'Atenciosamente,\n' +
          '[Nome da Equipe/Suporte]'
      }
    }
  },
  level: 'error',
  timestamp: '2025-09-29T15:46:50.418Z'
}
{
  message: 'Erro em processamento do job SendMessageChamado (ID: 2)',
  error: 'Error: 400: Bad Request: chat not found',
  stack: 'Error: Error: 400: Bad Request: chat not found\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendMessageChamado.js:90:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-29T15:46:50.420Z'
}
{
  error: Error: Error: 400: Bad Request: chat not found
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:90:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendMessageChamado] Job 2 falhou. Erro: Error: 400: Bad Request: chat not found',
  timestamp: '2025-09-29T15:46:50.644Z'
}
{
  message: 'Error send message api',
  error: TelegramError: 400: Bad Request: chat not found
      at Telegram.callApi (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\telegraf\lib\core\network\client.js:315:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:61:21)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24) {
    response: {
      ok: false,
      error_code: 400,
      description: 'Bad Request: chat not found'
    },
    on: {
      method: 'sendMessage',
      payload: {
        chat_id: '0',
        text: 'Olá,\n' +
          '\n' +
          'Seu chamado foi atualizado com as seguintes informações:\n' +
          '\n' +
          '🔹 ID do Chamado: 4\n' +
          '🔹 Assunto: Erros na nova versao a ser olhado\n' +
          '🔹 Técnico Responsável: Administrador Renato\n' +
          '\n' +
          'Erro 500 na rota https://fast.panelapps.site/email/send/4/close\n' +
          'Método da solicitação\n' +
          'POST\n' +
          '\n' +
          'Caso tenha alguma dúvida ou precise de mais informações, estamos à disposição.\n' +
          '\n' +
          'Atenciosamente,\n' +
          '[Nome da Equipe/Suporte]'
      }
    }
  },
  level: 'error',
  timestamp: '2025-09-29T15:46:52.559Z'
}
{
  message: 'Erro em processamento do job SendMessageChamado (ID: 2)',
  error: 'Error: 400: Bad Request: chat not found',
  stack: 'Error: Error: 400: Bad Request: chat not found\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendMessageChamado.js:90:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-29T15:46:52.560Z'
}
{
  error: Error: Error: 400: Bad Request: chat not found
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:90:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendMessageChamado] Job 2 falhou. Erro: Error: 400: Bad Request: chat not found',
  timestamp: '2025-09-29T15:46:52.782Z'
}
{
  message: 'Error send message api',
  error: TelegramError: 400: Bad Request: chat not found
      at Telegram.callApi (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\telegraf\lib\core\network\client.js:315:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:61:21)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24) {
    response: {
      ok: false,
      error_code: 400,
      description: 'Bad Request: chat not found'
    },
    on: {
      method: 'sendMessage',
      payload: {
        chat_id: '0',
        text: 'Olá,\n' +
          '\n' +
          'Seu chamado foi atualizado com as seguintes informações:\n' +
          '\n' +
          '🔹 ID do Chamado: 4\n' +
          '🔹 Assunto: Erros na nova versao a ser olhado\n' +
          '🔹 Técnico Responsável: Administrador Renato\n' +
          '\n' +
          'Erro 500 na rota https://fast.panelapps.site/email/send/4/close\n' +
          'Método da solicitação\n' +
          'POST\n' +
          '\n' +
          'Caso tenha alguma dúvida ou precise de mais informações, estamos à disposição.\n' +
          '\n' +
          'Atenciosamente,\n' +
          '[Nome da Equipe/Suporte]'
      }
    }
  },
  level: 'error',
  timestamp: '2025-09-29T15:46:54.955Z'
}
{
  message: 'Erro em processamento do job SendMessageChamado (ID: 2)',
  error: 'Error: 400: Bad Request: chat not found',
  stack: 'Error: Error: 400: Bad Request: chat not found\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendMessageChamado.js:90:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-29T15:46:54.956Z'
}
{
  error: Error: Error: 400: Bad Request: chat not found
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:90:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendMessageChamado] Job 2 falhou. Erro: Error: 400: Bad Request: chat not found',
  timestamp: '2025-09-29T15:46:55.178Z'
}
{
  message: 'Error send message api',
  error: TelegramError: 400: Bad Request: chat not found
      at Telegram.callApi (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\telegraf\lib\core\network\client.js:315:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:61:21)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24) {
    response: {
      ok: false,
      error_code: 400,
      description: 'Bad Request: chat not found'
    },
    on: {
      method: 'sendMessage',
      payload: {
        chat_id: '0',
        text: 'Olá,\n' +
          '\n' +
          'Seu chamado foi atualizado com as seguintes informações:\n' +
          '\n' +
          '🔹 ID do Chamado: 4\n' +
          '🔹 Assunto: Erros na nova versao a ser olhado\n' +
          '🔹 Técnico Responsável: Administrador Renato\n' +
          '\n' +
          'Erro 500 na rota https://fast.panelapps.site/email/send/4/close\n' +
          'Método da solicitação\n' +
          'POST\n' +
          '\n' +
          'Caso tenha alguma dúvida ou precise de mais informações, estamos à disposição.\n' +
          '\n' +
          'Atenciosamente,\n' +
          '[Nome da Equipe/Suporte]'
      }
    }
  },
  level: 'error',
  timestamp: '2025-09-29T15:46:57.103Z'
}
{
  message: 'Erro em processamento do job SendMessageChamado (ID: 2)',
  error: 'Error: 400: Bad Request: chat not found',
  stack: 'Error: Error: 400: Bad Request: chat not found\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendMessageChamado.js:90:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-29T15:46:57.104Z'
}
{
  error: Error: Error: 400: Bad Request: chat not found
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:90:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendMessageChamado] Job 2 falhou. Erro: Error: 400: Bad Request: chat not found',
  timestamp: '2025-09-29T15:46:57.326Z'
}
{
  message: 'Error send message api',
  error: TelegramError: 400: Bad Request: chat not found
      at Telegram.callApi (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\telegraf\lib\core\network\client.js:315:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:61:21)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24) {
    response: {
      ok: false,
      error_code: 400,
      description: 'Bad Request: chat not found'
    },
    on: {
      method: 'sendMessage',
      payload: {
        chat_id: '0',
        text: 'Olá,\n' +
          '\n' +
          'Seu chamado foi atualizado com as seguintes informações:\n' +
          '\n' +
          '🔹 ID do Chamado: 4\n' +
          '🔹 Assunto: Erros na nova versao a ser olhado\n' +
          '🔹 Técnico Responsável: Administrador Renato\n' +
          '\n' +
          'Erro 500 na rota https://fast.panelapps.site/email/send/4/close\n' +
          'Método da solicitação\n' +
          'POST\n' +
          '\n' +
          'Caso tenha alguma dúvida ou precise de mais informações, estamos à disposição.\n' +
          '\n' +
          'Atenciosamente,\n' +
          '[Nome da Equipe/Suporte]'
      }
    }
  },
  level: 'error',
  timestamp: '2025-09-29T15:46:59.230Z'
}
{
  message: 'Erro em processamento do job SendMessageChamado (ID: 2)',
  error: 'Error: 400: Bad Request: chat not found',
  stack: 'Error: Error: 400: Bad Request: chat not found\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendMessageChamado.js:90:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-29T15:46:59.232Z'
}
{
  error: Error: Error: 400: Bad Request: chat not found
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:90:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendMessageChamado] Job 2 falhou. Erro: Error: 400: Bad Request: chat not found',
  timestamp: '2025-09-29T15:46:59.457Z'
}
{
  message: 'Error send message api',
  error: TelegramError: 400: Bad Request: chat not found
      at Telegram.callApi (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\telegraf\lib\core\network\client.js:315:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:62:21)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24) {
    response: {
      ok: false,
      error_code: 400,
      description: 'Bad Request: chat not found'
    },
    on: {
      method: 'sendMessage',
      payload: {
        chat_id: '0',
        text: 'Olá,\n' +
          '\n' +
          'Seu chamado foi atualizado com as seguintes informações:\n' +
          '\n' +
          '🔹 ID do Chamado: 4\n' +
          '🔹 Assunto: Erros na nova versao a ser olhado\n' +
          '🔹 Técnico Responsável: Administrador Renato\n' +
          '\n' +
          'Erro 500 na rota https://fast.panelapps.site/email/send/4/close\n' +
          'Método da solicitação\n' +
          'POST\n' +
          '\n' +
          'Caso tenha alguma dúvida ou precise de mais informações, estamos à disposição.\n' +
          '\n' +
          'Atenciosamente,\n' +
          '[Nome da Equipe/Suporte]'
      }
    }
  },
  level: 'error',
  timestamp: '2025-09-29T15:48:24.436Z'
}
{
  message: 'Erro em processamento do job SendMessageChamado (ID: 3)',
  error: 'Error: 400: Bad Request: chat not found',
  stack: 'Error: Error: 400: Bad Request: chat not found\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendMessageChamado.js:91:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-29T15:48:24.438Z'
}
{
  error: Error: Error: 400: Bad Request: chat not found
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:91:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendMessageChamado] Job 3 falhou. Erro: Error: 400: Bad Request: chat not found',
  timestamp: '2025-09-29T15:48:24.661Z'
}
{
  message: 'Error send message api',
  error: TelegramError: 400: Bad Request: chat not found
      at Telegram.callApi (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\telegraf\lib\core\network\client.js:315:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:62:21)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24) {
    response: {
      ok: false,
      error_code: 400,
      description: 'Bad Request: chat not found'
    },
    on: {
      method: 'sendMessage',
      payload: {
        chat_id: '0',
        text: 'Olá,\n' +
          '\n' +
          'Seu chamado foi atualizado com as seguintes informações:\n' +
          '\n' +
          '🔹 ID do Chamado: 4\n' +
          '🔹 Assunto: Erros na nova versao a ser olhado\n' +
          '🔹 Técnico Responsável: Administrador Renato\n' +
          '\n' +
          'Ver a geracao pdf nota fiscal. dados da montagem da nota nao esta na Pasta DIST\n' +
          '\n' +
          'Caso tenha alguma dúvida ou precise de mais informações, estamos à disposição.\n' +
          '\n' +
          'Atenciosamente,\n' +
          '[Nome da Equipe/Suporte]'
      }
    }
  },
  level: 'error',
  timestamp: '2025-09-29T15:53:41.414Z'
}
{
  message: 'Erro em processamento do job SendMessageChamado (ID: 4)',
  error: 'Error: 400: Bad Request: chat not found',
  stack: 'Error: Error: 400: Bad Request: chat not found\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendMessageChamado.js:91:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-29T15:53:41.418Z'
}
{
  error: Error: Error: 400: Bad Request: chat not found
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:91:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendMessageChamado] Job 4 falhou. Erro: Error: 400: Bad Request: chat not found',
  timestamp: '2025-09-29T15:53:41.638Z'
}
{
  message: 'Error send message api',
  error: TelegramError: 400: Bad Request: chat not found
      at Telegram.callApi (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\telegraf\lib\core\network\client.js:315:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:62:21)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24) {
    response: {
      ok: false,
      error_code: 400,
      description: 'Bad Request: chat not found'
    },
    on: {
      method: 'sendMessage',
      payload: {
        chat_id: '0',
        text: 'Olá,\n' +
          '\n' +
          'Seu chamado foi atualizado com as seguintes informações:\n' +
          '\n' +
          '🔹 ID do Chamado: 4\n' +
          '🔹 Assunto: Erros na nova versao a ser olhado\n' +
          '🔹 Técnico Responsável: Administrador Renato\n' +
          '\n' +
          'Ver a geracao pdf nota fiscal. dados da montagem da nota nao esta na Pasta DIST\n' +
          '\n' +
          'Caso tenha alguma dúvida ou precise de mais informações, estamos à disposição.\n' +
          '\n' +
          'Atenciosamente,\n' +
          '[Nome da Equipe/Suporte]'
      }
    }
  },
  level: 'error',
  timestamp: '2025-09-29T15:55:28.622Z'
}
{
  message: 'Erro em processamento do job SendMessageChamado (ID: 5)',
  error: 'Error: 400: Bad Request: chat not found',
  stack: 'Error: Error: 400: Bad Request: chat not found\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendMessageChamado.js:91:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-29T15:55:28.623Z'
}
{
  error: Error: Error: 400: Bad Request: chat not found
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:91:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendMessageChamado] Job 5 falhou. Erro: Error: 400: Bad Request: chat not found',
  timestamp: '2025-09-29T15:55:28.842Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 4)',
  error: 'The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  stack: 'TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object\n' +
    '    at _write (node:internal/streams/writable:482:13)\n' +
    '    at Writable.end (node:internal/streams/writable:823:17)\n' +
    '    at Immediate.<anonymous> (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\nodemailer\\lib\\mime-node\\index.js:997:35)\n' +
    '    at process.processImmediate (node:internal/timers:485:21)',
  level: 'error',
  timestamp: '2025-09-30T11:17:09.285Z'
}
{
  error: TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
      at _write (node:internal/streams/writable:482:13)
      at Writable.end (node:internal/streams/writable:823:17)
      at Immediate.<anonymous> (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\nodemailer\lib\mime-node\index.js:997:35)
      at process.processImmediate (node:internal/timers:485:21) {
    code: 'ESTREAM',
    command: 'API'
  },
  level: 'error',
  message: '[Worker SendEmail] Job 4 falhou. Erro: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  timestamp: '2025-09-30T11:17:09.509Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 4)',
  error: 'The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  stack: 'TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object\n' +
    '    at _write (node:internal/streams/writable:482:13)\n' +
    '    at Writable.end (node:internal/streams/writable:823:17)\n' +
    '    at Immediate.<anonymous> (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\nodemailer\\lib\\mime-node\\index.js:997:35)\n' +
    '    at process.processImmediate (node:internal/timers:485:21)',
  level: 'error',
  timestamp: '2025-09-30T11:17:11.393Z'
}
{
  error: TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
      at _write (node:internal/streams/writable:482:13)
      at Writable.end (node:internal/streams/writable:823:17)
      at Immediate.<anonymous> (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\nodemailer\lib\mime-node\index.js:997:35)
      at process.processImmediate (node:internal/timers:485:21) {
    code: 'ESTREAM',
    command: 'API'
  },
  level: 'error',
  message: '[Worker SendEmail] Job 4 falhou. Erro: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  timestamp: '2025-09-30T11:17:11.610Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 4)',
  error: 'The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  stack: 'TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object\n' +
    '    at _write (node:internal/streams/writable:482:13)\n' +
    '    at Writable.end (node:internal/streams/writable:823:17)\n' +
    '    at Immediate.<anonymous> (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\nodemailer\\lib\\mime-node\\index.js:997:35)\n' +
    '    at process.processImmediate (node:internal/timers:485:21)',
  level: 'error',
  timestamp: '2025-09-30T11:17:13.612Z'
}
{
  error: TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
      at _write (node:internal/streams/writable:482:13)
      at Writable.end (node:internal/streams/writable:823:17)
      at Immediate.<anonymous> (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\nodemailer\lib\mime-node\index.js:997:35)
      at process.processImmediate (node:internal/timers:485:21) {
    code: 'ESTREAM',
    command: 'API'
  },
  level: 'error',
  message: '[Worker SendEmail] Job 4 falhou. Erro: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  timestamp: '2025-09-30T11:17:13.829Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 4)',
  error: 'The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  stack: 'TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object\n' +
    '    at _write (node:internal/streams/writable:482:13)\n' +
    '    at Writable.end (node:internal/streams/writable:823:17)\n' +
    '    at Immediate.<anonymous> (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\nodemailer\\lib\\mime-node\\index.js:997:35)\n' +
    '    at process.processImmediate (node:internal/timers:485:21)',
  level: 'error',
  timestamp: '2025-09-30T11:17:15.905Z'
}
{
  error: TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
      at _write (node:internal/streams/writable:482:13)
      at Writable.end (node:internal/streams/writable:823:17)
      at Immediate.<anonymous> (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\nodemailer\lib\mime-node\index.js:997:35)
      at process.processImmediate (node:internal/timers:485:21) {
    code: 'ESTREAM',
    command: 'API'
  },
  level: 'error',
  message: '[Worker SendEmail] Job 4 falhou. Erro: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  timestamp: '2025-09-30T11:17:16.122Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 4)',
  error: 'The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  stack: 'TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object\n' +
    '    at _write (node:internal/streams/writable:482:13)\n' +
    '    at Writable.end (node:internal/streams/writable:823:17)\n' +
    '    at Immediate.<anonymous> (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\nodemailer\\lib\\mime-node\\index.js:997:35)\n' +
    '    at process.processImmediate (node:internal/timers:485:21)',
  level: 'error',
  timestamp: '2025-09-30T11:17:18.149Z'
}
{
  error: TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
      at _write (node:internal/streams/writable:482:13)
      at Writable.end (node:internal/streams/writable:823:17)
      at Immediate.<anonymous> (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\nodemailer\lib\mime-node\index.js:997:35)
      at process.processImmediate (node:internal/timers:485:21) {
    code: 'ESTREAM',
    command: 'API'
  },
  level: 'error',
  message: '[Worker SendEmail] Job 4 falhou. Erro: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  timestamp: '2025-09-30T11:17:18.365Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 5)',
  error: 'The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  stack: 'TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object\n' +
    '    at _write (node:internal/streams/writable:482:13)\n' +
    '    at Writable.end (node:internal/streams/writable:823:17)\n' +
    '    at Immediate.<anonymous> (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\nodemailer\\lib\\mime-node\\index.js:997:35)\n' +
    '    at process.processImmediate (node:internal/timers:485:21)',
  level: 'error',
  timestamp: '2025-09-30T11:17:24.448Z'
}
{
  error: TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
      at _write (node:internal/streams/writable:482:13)
      at Writable.end (node:internal/streams/writable:823:17)
      at Immediate.<anonymous> (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\nodemailer\lib\mime-node\index.js:997:35)
      at process.processImmediate (node:internal/timers:485:21) {
    code: 'ESTREAM',
    command: 'API'
  },
  level: 'error',
  message: '[Worker SendEmail] Job 5 falhou. Erro: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  timestamp: '2025-09-30T11:17:24.666Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 5)',
  error: 'The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  stack: 'TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object\n' +
    '    at _write (node:internal/streams/writable:482:13)\n' +
    '    at Writable.end (node:internal/streams/writable:823:17)\n' +
    '    at Immediate.<anonymous> (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\nodemailer\\lib\\mime-node\\index.js:997:35)\n' +
    '    at process.processImmediate (node:internal/timers:485:21)',
  level: 'error',
  timestamp: '2025-09-30T11:17:26.565Z'
}
{
  error: TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
      at _write (node:internal/streams/writable:482:13)
      at Writable.end (node:internal/streams/writable:823:17)
      at Immediate.<anonymous> (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\nodemailer\lib\mime-node\index.js:997:35)
      at process.processImmediate (node:internal/timers:485:21) {
    code: 'ESTREAM',
    command: 'API'
  },
  level: 'error',
  message: '[Worker SendEmail] Job 5 falhou. Erro: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  timestamp: '2025-09-30T11:17:26.782Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 5)',
  error: 'The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  stack: 'TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object\n' +
    '    at _write (node:internal/streams/writable:482:13)\n' +
    '    at Writable.end (node:internal/streams/writable:823:17)\n' +
    '    at Immediate.<anonymous> (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\nodemailer\\lib\\mime-node\\index.js:997:35)\n' +
    '    at process.processImmediate (node:internal/timers:485:21)',
  level: 'error',
  timestamp: '2025-09-30T11:17:28.825Z'
}
{
  error: TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
      at _write (node:internal/streams/writable:482:13)
      at Writable.end (node:internal/streams/writable:823:17)
      at Immediate.<anonymous> (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\nodemailer\lib\mime-node\index.js:997:35)
      at process.processImmediate (node:internal/timers:485:21) {
    code: 'ESTREAM',
    command: 'API'
  },
  level: 'error',
  message: '[Worker SendEmail] Job 5 falhou. Erro: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  timestamp: '2025-09-30T11:17:29.041Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 5)',
  error: 'The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  stack: 'TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object\n' +
    '    at _write (node:internal/streams/writable:482:13)\n' +
    '    at Writable.end (node:internal/streams/writable:823:17)\n' +
    '    at Immediate.<anonymous> (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\nodemailer\\lib\\mime-node\\index.js:997:35)\n' +
    '    at process.processImmediate (node:internal/timers:485:21)',
  level: 'error',
  timestamp: '2025-09-30T11:17:30.974Z'
}
{
  error: TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
      at _write (node:internal/streams/writable:482:13)
      at Writable.end (node:internal/streams/writable:823:17)
      at Immediate.<anonymous> (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\nodemailer\lib\mime-node\index.js:997:35)
      at process.processImmediate (node:internal/timers:485:21) {
    code: 'ESTREAM',
    command: 'API'
  },
  level: 'error',
  message: '[Worker SendEmail] Job 5 falhou. Erro: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  timestamp: '2025-09-30T11:17:31.190Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 5)',
  error: 'The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  stack: 'TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object\n' +
    '    at _write (node:internal/streams/writable:482:13)\n' +
    '    at Writable.end (node:internal/streams/writable:823:17)\n' +
    '    at Immediate.<anonymous> (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\nodemailer\\lib\\mime-node\\index.js:997:35)\n' +
    '    at process.processImmediate (node:internal/timers:485:21)',
  level: 'error',
  timestamp: '2025-09-30T11:17:33.181Z'
}
{
  error: TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
      at _write (node:internal/streams/writable:482:13)
      at Writable.end (node:internal/streams/writable:823:17)
      at Immediate.<anonymous> (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\nodemailer\lib\mime-node\index.js:997:35)
      at process.processImmediate (node:internal/timers:485:21) {
    code: 'ESTREAM',
    command: 'API'
  },
  level: 'error',
  message: '[Worker SendEmail] Job 5 falhou. Erro: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  timestamp: '2025-09-30T11:17:33.397Z'
}
{
  error: [Error: ENOENT: no such file or directory, open 'C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\public\attachments\chat bot new_26092025164445020.json'] {
    errno: -4058,
    code: 'ENOENT',
    syscall: 'open',
    path: 'C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\chat bot new_26092025164445020.json'
  },
  level: 'error',
  message: "uncaughtException: ENOENT: no such file or directory, open 'C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\chat bot new_26092025164445020.json'\n" +
    "Error: ENOENT: no such file or directory, open 'C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\chat bot new_26092025164445020.json'",
  stack: "Error: ENOENT: no such file or directory, open 'C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\chat bot new_26092025164445020.json'",
  exception: true,
  date: 'Tue Sep 30 2025 08:18:19 GMT-0300 (Horário Padrão de Brasília)',
  process: {
    pid: 13872,
    uid: null,
    gid: null,
    cwd: 'C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify',
    execPath: 'C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Port\\app\\node.exe',
    version: 'v22.19.0',
    argv: [
      'C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Port\\app\\node.exe',
      'C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\server.js'
    ],
    memoryUsage: {
      rss: 119947264,
      heapTotal: 74264576,
      heapUsed: 64455492,
      external: 4727531,
      arrayBuffers: 840197
    }
  },
  os: { loadavg: [ 0, 0, 0 ], uptime: 5717.609 },
  trace: [],
  timestamp: '2025-09-30T11:18:19.824Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 14)',
  error: 'The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  stack: 'TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object\n' +
    '    at _write (node:internal/streams/writable:482:13)\n' +
    '    at Writable.end (node:internal/streams/writable:823:17)\n' +
    '    at Immediate.<anonymous> (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\nodemailer\\lib\\mime-node\\index.js:997:35)\n' +
    '    at process.processImmediate (node:internal/timers:485:21)',
  level: 'error',
  timestamp: '2025-09-30T11:27:38.481Z'
}
{
  error: TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
      at _write (node:internal/streams/writable:482:13)
      at Writable.end (node:internal/streams/writable:823:17)
      at Immediate.<anonymous> (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\nodemailer\lib\mime-node\index.js:997:35)
      at process.processImmediate (node:internal/timers:485:21) {
    code: 'ESTREAM',
    command: 'API'
  },
  level: 'error',
  message: '[Worker SendEmail] Job 14 falhou. Erro: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  timestamp: '2025-09-30T11:27:38.709Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 16)',
  error: 'The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  stack: 'TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object\n' +
    '    at _write (node:internal/streams/writable:482:13)\n' +
    '    at Writable.end (node:internal/streams/writable:823:17)\n' +
    '    at Immediate.<anonymous> (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\nodemailer\\lib\\mime-node\\index.js:997:35)\n' +
    '    at process.processImmediate (node:internal/timers:485:21)',
  level: 'error',
  timestamp: '2025-09-30T11:29:38.092Z'
}
{
  error: TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
      at _write (node:internal/streams/writable:482:13)
      at Writable.end (node:internal/streams/writable:823:17)
      at Immediate.<anonymous> (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\nodemailer\lib\mime-node\index.js:997:35)
      at process.processImmediate (node:internal/timers:485:21) {
    code: 'ESTREAM',
    command: 'API'
  },
  level: 'error',
  message: '[Worker SendEmail] Job 16 falhou. Erro: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  timestamp: '2025-09-30T11:29:38.317Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 17)',
  error: 'The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  stack: 'TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object\n' +
    '    at _write (node:internal/streams/writable:482:13)\n' +
    '    at Writable.end (node:internal/streams/writable:823:17)\n' +
    '    at Immediate.<anonymous> (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\nodemailer\\lib\\mime-node\\index.js:997:35)\n' +
    '    at process.processImmediate (node:internal/timers:485:21)',
  level: 'error',
  timestamp: '2025-09-30T11:31:19.035Z'
}
{
  error: TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
      at _write (node:internal/streams/writable:482:13)
      at Writable.end (node:internal/streams/writable:823:17)
      at Immediate.<anonymous> (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\nodemailer\lib\mime-node\index.js:997:35)
      at process.processImmediate (node:internal/timers:485:21) {
    code: 'ESTREAM',
    command: 'API'
  },
  level: 'error',
  message: '[Worker SendEmail] Job 17 falhou. Erro: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  timestamp: '2025-09-30T11:31:19.260Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 18)',
  error: 'The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  stack: 'TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object\n' +
    '    at _write (node:internal/streams/writable:482:13)\n' +
    '    at Writable.end (node:internal/streams/writable:823:17)\n' +
    '    at Immediate.<anonymous> (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\nodemailer\\lib\\mime-node\\index.js:997:35)\n' +
    '    at process.processImmediate (node:internal/timers:485:21)',
  level: 'error',
  timestamp: '2025-09-30T11:32:33.429Z'
}
{
  error: TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
      at _write (node:internal/streams/writable:482:13)
      at Writable.end (node:internal/streams/writable:823:17)
      at Immediate.<anonymous> (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\nodemailer\lib\mime-node\index.js:997:35)
      at process.processImmediate (node:internal/timers:485:21) {
    code: 'ESTREAM',
    command: 'API'
  },
  level: 'error',
  message: '[Worker SendEmail] Job 18 falhou. Erro: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  timestamp: '2025-09-30T11:32:33.652Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 19)',
  error: 'The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  stack: 'TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object\n' +
    '    at _write (node:internal/streams/writable:482:13)\n' +
    '    at Writable.end (node:internal/streams/writable:823:17)\n' +
    '    at Immediate.<anonymous> (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\nodemailer\\lib\\mime-node\\index.js:997:35)\n' +
    '    at process.processImmediate (node:internal/timers:485:21)',
  level: 'error',
  timestamp: '2025-09-30T11:33:29.770Z'
}
{
  error: TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
      at _write (node:internal/streams/writable:482:13)
      at Writable.end (node:internal/streams/writable:823:17)
      at Immediate.<anonymous> (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\nodemailer\lib\mime-node\index.js:997:35)
      at process.processImmediate (node:internal/timers:485:21) {
    code: 'ESTREAM',
    command: 'API'
  },
  level: 'error',
  message: '[Worker SendEmail] Job 19 falhou. Erro: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  timestamp: '2025-09-30T11:33:29.992Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 20)',
  error: 'The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  stack: 'TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object\n' +
    '    at _write (node:internal/streams/writable:482:13)\n' +
    '    at Writable.end (node:internal/streams/writable:823:17)\n' +
    '    at Immediate.<anonymous> (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\nodemailer\\lib\\mime-node\\index.js:997:35)\n' +
    '    at process.processImmediate (node:internal/timers:485:21)',
  level: 'error',
  timestamp: '2025-09-30T11:34:43.772Z'
}
{
  error: TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
      at _write (node:internal/streams/writable:482:13)
      at Writable.end (node:internal/streams/writable:823:17)
      at Immediate.<anonymous> (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\nodemailer\lib\mime-node\index.js:997:35)
      at process.processImmediate (node:internal/timers:485:21) {
    code: 'ESTREAM',
    command: 'API'
  },
  level: 'error',
  message: '[Worker SendEmail] Job 20 falhou. Erro: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  timestamp: '2025-09-30T11:34:43.999Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 21)',
  error: 'The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  stack: 'TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object\n' +
    '    at _write (node:internal/streams/writable:482:13)\n' +
    '    at Writable.end (node:internal/streams/writable:823:17)\n' +
    '    at Immediate.<anonymous> (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\nodemailer\\lib\\mime-node\\index.js:997:35)\n' +
    '    at process.processImmediate (node:internal/timers:485:21)',
  level: 'error',
  timestamp: '2025-09-30T11:45:50.063Z'
}
{
  error: TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
      at _write (node:internal/streams/writable:482:13)
      at Writable.end (node:internal/streams/writable:823:17)
      at Immediate.<anonymous> (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\nodemailer\lib\mime-node\index.js:997:35)
      at process.processImmediate (node:internal/timers:485:21) {
    code: 'ESTREAM',
    command: 'API'
  },
  level: 'error',
  message: '[Worker SendEmail] Job 21 falhou. Erro: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  timestamp: '2025-09-30T11:45:50.282Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 22)',
  error: 'The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  stack: 'TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object\n' +
    '    at _write (node:internal/streams/writable:482:13)\n' +
    '    at Writable.end (node:internal/streams/writable:823:17)\n' +
    '    at Immediate.<anonymous> (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\nodemailer\\lib\\mime-node\\index.js:997:35)\n' +
    '    at process.processImmediate (node:internal/timers:485:21)',
  level: 'error',
  timestamp: '2025-09-30T11:46:21.498Z'
}
{
  error: TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
      at _write (node:internal/streams/writable:482:13)
      at Writable.end (node:internal/streams/writable:823:17)
      at Immediate.<anonymous> (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\nodemailer\lib\mime-node\index.js:997:35)
      at process.processImmediate (node:internal/timers:485:21) {
    code: 'ESTREAM',
    command: 'API'
  },
  level: 'error',
  message: '[Worker SendEmail] Job 22 falhou. Erro: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  timestamp: '2025-09-30T11:46:21.722Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 23)',
  error: 'The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  stack: 'TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object\n' +
    '    at _write (node:internal/streams/writable:482:13)\n' +
    '    at Writable.end (node:internal/streams/writable:823:17)\n' +
    '    at Immediate.<anonymous> (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\nodemailer\\lib\\mime-node\\index.js:997:35)\n' +
    '    at process.processImmediate (node:internal/timers:485:21)',
  level: 'error',
  timestamp: '2025-09-30T11:47:22.344Z'
}
{
  error: TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
      at _write (node:internal/streams/writable:482:13)
      at Writable.end (node:internal/streams/writable:823:17)
      at Immediate.<anonymous> (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\nodemailer\lib\mime-node\index.js:997:35)
      at process.processImmediate (node:internal/timers:485:21) {
    code: 'ESTREAM',
    command: 'API'
  },
  level: 'error',
  message: '[Worker SendEmail] Job 23 falhou. Erro: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  timestamp: '2025-09-30T11:47:22.569Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 25)',
  error: 'The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  stack: 'TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object\n' +
    '    at _write (node:internal/streams/writable:482:13)\n' +
    '    at Writable.end (node:internal/streams/writable:823:17)\n' +
    '    at Immediate.<anonymous> (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\nodemailer\\lib\\mime-node\\index.js:997:35)\n' +
    '    at process.processImmediate (node:internal/timers:485:21)',
  level: 'error',
  timestamp: '2025-09-30T11:49:23.663Z'
}
{
  error: TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
      at _write (node:internal/streams/writable:482:13)
      at Writable.end (node:internal/streams/writable:823:17)
      at Immediate.<anonymous> (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\nodemailer\lib\mime-node\index.js:997:35)
      at process.processImmediate (node:internal/timers:485:21) {
    code: 'ESTREAM',
    command: 'API'
  },
  level: 'error',
  message: '[Worker SendEmail] Job 25 falhou. Erro: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  timestamp: '2025-09-30T11:49:23.887Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 26)',
  error: 'The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  stack: 'TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object\n' +
    '    at _write (node:internal/streams/writable:482:13)\n' +
    '    at Writable.end (node:internal/streams/writable:823:17)\n' +
    '    at Immediate.<anonymous> (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\nodemailer\\lib\\mime-node\\index.js:997:35)\n' +
    '    at process.processImmediate (node:internal/timers:485:21)',
  level: 'error',
  timestamp: '2025-09-30T11:50:21.914Z'
}
{
  error: TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
      at _write (node:internal/streams/writable:482:13)
      at Writable.end (node:internal/streams/writable:823:17)
      at Immediate.<anonymous> (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\nodemailer\lib\mime-node\index.js:997:35)
      at process.processImmediate (node:internal/timers:485:21) {
    code: 'ESTREAM',
    command: 'API'
  },
  level: 'error',
  message: '[Worker SendEmail] Job 26 falhou. Erro: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  timestamp: '2025-09-30T11:50:22.138Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 27)',
  error: 'The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  stack: 'TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object\n' +
    '    at _write (node:internal/streams/writable:482:13)\n' +
    '    at Writable.end (node:internal/streams/writable:823:17)\n' +
    '    at Immediate.<anonymous> (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\nodemailer\\lib\\mime-node\\index.js:997:35)\n' +
    '    at process.processImmediate (node:internal/timers:485:21)',
  level: 'error',
  timestamp: '2025-09-30T11:51:20.923Z'
}
{
  error: TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
      at _write (node:internal/streams/writable:482:13)
      at Writable.end (node:internal/streams/writable:823:17)
      at Immediate.<anonymous> (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\nodemailer\lib\mime-node\index.js:997:35)
      at process.processImmediate (node:internal/timers:485:21) {
    code: 'ESTREAM',
    command: 'API'
  },
  level: 'error',
  message: '[Worker SendEmail] Job 27 falhou. Erro: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  timestamp: '2025-09-30T11:51:21.146Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 28)',
  error: 'The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  stack: 'TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object\n' +
    '    at _write (node:internal/streams/writable:482:13)\n' +
    '    at Writable.end (node:internal/streams/writable:823:17)\n' +
    '    at Immediate.<anonymous> (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\nodemailer\\lib\\mime-node\\index.js:997:35)\n' +
    '    at process.processImmediate (node:internal/timers:485:21)',
  level: 'error',
  timestamp: '2025-09-30T11:54:10.488Z'
}
{
  error: TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
      at _write (node:internal/streams/writable:482:13)
      at Writable.end (node:internal/streams/writable:823:17)
      at Immediate.<anonymous> (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\nodemailer\lib\mime-node\index.js:997:35)
      at process.processImmediate (node:internal/timers:485:21) {
    code: 'ESTREAM',
    command: 'API'
  },
  level: 'error',
  message: '[Worker SendEmail] Job 28 falhou. Erro: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  timestamp: '2025-09-30T11:54:10.710Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 30)',
  error: 'The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  stack: 'TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object\n' +
    '    at _write (node:internal/streams/writable:482:13)\n' +
    '    at Writable.end (node:internal/streams/writable:823:17)\n' +
    '    at Immediate.<anonymous> (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\nodemailer\\lib\\mime-node\\index.js:997:35)\n' +
    '    at process.processImmediate (node:internal/timers:485:21)',
  level: 'error',
  timestamp: '2025-09-30T11:56:37.073Z'
}
{
  error: TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
      at _write (node:internal/streams/writable:482:13)
      at Writable.end (node:internal/streams/writable:823:17)
      at Immediate.<anonymous> (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\nodemailer\lib\mime-node\index.js:997:35)
      at process.processImmediate (node:internal/timers:485:21) {
    code: 'ESTREAM',
    command: 'API'
  },
  level: 'error',
  message: '[Worker SendEmail] Job 30 falhou. Erro: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  timestamp: '2025-09-30T11:56:37.296Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 33)',
  error: 'The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  stack: 'TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object\n' +
    '    at _write (node:internal/streams/writable:482:13)\n' +
    '    at Writable.end (node:internal/streams/writable:823:17)\n' +
    '    at Immediate.<anonymous> (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\nodemailer\\lib\\mime-node\\index.js:997:35)\n' +
    '    at process.processImmediate (node:internal/timers:485:21)',
  level: 'error',
  timestamp: '2025-09-30T11:59:51.749Z'
}
{
  error: TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
      at _write (node:internal/streams/writable:482:13)
      at Writable.end (node:internal/streams/writable:823:17)
      at Immediate.<anonymous> (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\nodemailer\lib\mime-node\index.js:997:35)
      at process.processImmediate (node:internal/timers:485:21) {
    code: 'ESTREAM',
    command: 'API'
  },
  level: 'error',
  message: '[Worker SendEmail] Job 33 falhou. Erro: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  timestamp: '2025-09-30T11:59:51.966Z'
}
{
  code: 'ESTREAM',
  command: 'API',
  level: 'error',
  message: 'DEPURAÇÃO: O erro ocorreu mesmo com o anexo codificado. The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  stack: 'TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object\n' +
    '    at _write (node:internal/streams/writable:482:13)\n' +
    '    at Writable.end (node:internal/streams/writable:823:17)\n' +
    '    at Immediate.<anonymous> (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\nodemailer\\lib\\mime-node\\index.js:997:35)\n' +
    '    at process.processImmediate (node:internal/timers:485:21)',
  timestamp: '2025-09-30T12:03:05.549Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 35)',
  error: 'The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  stack: 'TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object\n' +
    '    at _write (node:internal/streams/writable:482:13)\n' +
    '    at Writable.end (node:internal/streams/writable:823:17)\n' +
    '    at Immediate.<anonymous> (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\nodemailer\\lib\\mime-node\\index.js:997:35)\n' +
    '    at process.processImmediate (node:internal/timers:485:21)',
  level: 'error',
  timestamp: '2025-09-30T12:03:05.551Z'
}
{
  error: TypeError [ESTREAM]: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
      at _write (node:internal/streams/writable:482:13)
      at Writable.end (node:internal/streams/writable:823:17)
      at Immediate.<anonymous> (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\nodemailer\lib\mime-node\index.js:997:35)
      at process.processImmediate (node:internal/timers:485:21) {
    code: 'ESTREAM',
    command: 'API'
  },
  level: 'error',
  message: '[Worker SendEmail] Job 35 falhou. Erro: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object',
  timestamp: '2025-09-30T12:03:05.777Z'
}
{
  message: 'Error send message api',
  error: TelegramError: 400: Bad Request: IMAGE_PROCESS_FAILED
      at Telegram.callApi (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\telegraf\lib\core\network\client.js:315:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:50:25)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24) {
    response: {
      ok: false,
      error_code: 400,
      description: 'Bad Request: IMAGE_PROCESS_FAILED'
    },
    on: {
      method: 'sendPhoto',
      payload: {
        chat_id: '1015137420',
        photo: {
          source: 'C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\chat bot new.json'
        },
        caption: 'Olá,\n' +
          '\n' +
          'Seu chamado foi atualizado com as seguintes informações:\n' +
          '\n' +
          '🔹 ID do Chamado: 4\n' +
          '🔹 Assunto: Erros na nova versao a ser olhado\n' +
          '🔹 Técnico Responsável: Renato\n' +
          '\n' +
          '513\n' +
          '\n' +
          'Caso tenha alguma dúvida ou precise de mais informações, estamos à disposição.\n' +
          '\n' +
          'Atenciosamente,\n' +
          '[Nome da Equipe/Suporte]'
      }
    }
  },
  level: 'error',
  timestamp: '2025-09-30T12:21:05.196Z'
}
{
  message: 'Erro em processamento do job SendMessageChamado (ID: 8)',
  error: 'Error: 400: Bad Request: IMAGE_PROCESS_FAILED',
  stack: 'Error: Error: 400: Bad Request: IMAGE_PROCESS_FAILED\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendMessageChamado.js:90:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-30T12:21:05.198Z'
}
{
  error: Error: Error: 400: Bad Request: IMAGE_PROCESS_FAILED
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:90:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendMessageChamado] Job 8 falhou. Erro: Error: 400: Bad Request: IMAGE_PROCESS_FAILED',
  timestamp: '2025-09-30T12:21:05.413Z'
}
{
  message: 'Error send message api',
  error: TelegramError: 400: Bad Request: IMAGE_PROCESS_FAILED
      at Telegram.callApi (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\telegraf\lib\core\network\client.js:315:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:50:25)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24) {
    response: {
      ok: false,
      error_code: 400,
      description: 'Bad Request: IMAGE_PROCESS_FAILED'
    },
    on: {
      method: 'sendPhoto',
      payload: {
        chat_id: '1015137420',
        photo: {
          source: 'C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\chat bot new.json'
        },
        caption: 'Olá,\n' +
          '\n' +
          'Seu chamado foi atualizado com as seguintes informações:\n' +
          '\n' +
          '🔹 ID do Chamado: 4\n' +
          '🔹 Assunto: Erros na nova versao a ser olhado\n' +
          '🔹 Técnico Responsável: Renato\n' +
          '\n' +
          '43223423423\n' +
          '\n' +
          'Caso tenha alguma dúvida ou precise de mais informações, estamos à disposição.\n' +
          '\n' +
          'Atenciosamente,\n' +
          '[Nome da Equipe/Suporte]'
      }
    }
  },
  level: 'error',
  timestamp: '2025-09-30T12:28:40.056Z'
}
{
  message: 'Erro em processamento do job SendMessageChamado (ID: 9)',
  error: 'Error: 400: Bad Request: IMAGE_PROCESS_FAILED',
  stack: 'Error: Error: 400: Bad Request: IMAGE_PROCESS_FAILED\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendMessageChamado.js:90:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-30T12:28:40.061Z'
}
{
  error: Error: Error: 400: Bad Request: IMAGE_PROCESS_FAILED
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:90:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendMessageChamado] Job 9 falhou. Erro: Error: 400: Bad Request: IMAGE_PROCESS_FAILED',
  timestamp: '2025-09-30T12:28:40.284Z'
}
{
  message: 'Error send message api',
  error: TelegramError: 400: Bad Request: IMAGE_PROCESS_FAILED
      at Telegram.callApi (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\telegraf\lib\core\network\client.js:315:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:50:25)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24) {
    response: {
      ok: false,
      error_code: 400,
      description: 'Bad Request: IMAGE_PROCESS_FAILED'
    },
    on: {
      method: 'sendPhoto',
      payload: {
        chat_id: '1015137420',
        photo: {
          source: 'C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\chat bot new.json'
        },
        caption: 'Olá,\n' +
          '\n' +
          'Seu chamado foi atualizado com as seguintes informações:\n' +
          '\n' +
          '🔹 ID do Chamado: 4\n' +
          '🔹 Assunto: Erros na nova versao a ser olhado\n' +
          '🔹 Técnico Responsável: Renato\n' +
          '\n' +
          '2122121\n' +
          '\n' +
          'Caso tenha alguma dúvida ou precise de mais informações, estamos à disposição.\n' +
          '\n' +
          'Atenciosamente,\n' +
          '[Nome da Equipe/Suporte]'
      }
    }
  },
  level: 'error',
  timestamp: '2025-09-30T12:29:37.040Z'
}
{
  message: 'Erro em processamento do job SendMessageChamado (ID: 10)',
  error: 'Error: 400: Bad Request: IMAGE_PROCESS_FAILED',
  stack: 'Error: Error: 400: Bad Request: IMAGE_PROCESS_FAILED\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendMessageChamado.js:96:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-30T12:29:37.044Z'
}
{
  error: Error: Error: 400: Bad Request: IMAGE_PROCESS_FAILED
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:96:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendMessageChamado] Job 10 falhou. Erro: Error: 400: Bad Request: IMAGE_PROCESS_FAILED',
  timestamp: '2025-09-30T12:29:37.266Z'
}
{
  message: 'Error send message api',
  error: TelegramError: 400: Bad Request: IMAGE_PROCESS_FAILED
      at Telegram.callApi (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\telegraf\lib\core\network\client.js:315:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:51:25)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24) {
    response: {
      ok: false,
      error_code: 400,
      description: 'Bad Request: IMAGE_PROCESS_FAILED'
    },
    on: {
      method: 'sendPhoto',
      payload: {
        chat_id: '1015137420',
        photo: {
          source: 'C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\chat bot new.json'
        },
        caption: 'Olá,\n' +
          '\n' +
          'Seu chamado foi atualizado com as seguintes informações:\n' +
          '\n' +
          '🔹 ID do Chamado: 4\n' +
          '🔹 Assunto: Erros na nova versao a ser olhado\n' +
          '🔹 Técnico Responsável: Renato\n' +
          '\n' +
          '234234\n' +
          '\n' +
          'Caso tenha alguma dúvida ou precise de mais informações, estamos à disposição.\n' +
          '\n' +
          'Atenciosamente,\n' +
          '[Nome da Equipe/Suporte]'
      }
    }
  },
  level: 'error',
  timestamp: '2025-09-30T12:31:08.021Z'
}
{
  message: 'Erro em processamento do job SendMessageChamado (ID: 12)',
  error: 'Error: 400: Bad Request: IMAGE_PROCESS_FAILED',
  stack: 'Error: Error: 400: Bad Request: IMAGE_PROCESS_FAILED\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendMessageChamado.js:91:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-30T12:31:08.024Z'
}
{
  error: Error: Error: 400: Bad Request: IMAGE_PROCESS_FAILED
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:91:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendMessageChamado] Job 12 falhou. Erro: Error: 400: Bad Request: IMAGE_PROCESS_FAILED',
  timestamp: '2025-09-30T12:31:08.247Z'
}
{
  message: 'Error send message api',
  error: TelegramError: 400: Bad Request: IMAGE_PROCESS_FAILED
      at Telegram.callApi (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\telegraf\lib\core\network\client.js:315:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:52:25)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24) {
    response: {
      ok: false,
      error_code: 400,
      description: 'Bad Request: IMAGE_PROCESS_FAILED'
    },
    on: {
      method: 'sendPhoto',
      payload: {
        chat_id: '1015137420',
        photo: {
          source: ReadStream {
            fd: null,
            path: 'C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\chat bot new.json',
            flags: 'r',
            mode: 438,
            start: undefined,
            end: Infinity,
            pos: undefined,
            bytesRead: 86637,
            _events: {
              close: undefined,
              error: undefined,
              data: undefined,
              end: undefined,
              readable: undefined,
              [Symbol(kConstruct)]: undefined
            },
            _readableState: ReadableState {
              highWaterMark: 65536,
              buffer: [],
              bufferIndex: 0,
              length: 0,
              pipes: [],
              awaitDrainWriters: null,
              [Symbol(kState)]: 110626684
            },
            _maxListeners: undefined,
            _eventsCount: 0,
            [Symbol(kFs)]: {
              appendFile: [Function: appendFile],
              appendFileSync: [Function: appendFileSync],
              access: [Function: access],
              accessSync: [Function: accessSync],
              chown: [Function: chown],
              chownSync: [Function: chownSync],
              chmod: [Function: chmod],
              chmodSync: [Function: chmodSync],
              close: [Function: close],
              closeSync: [Function: closeSync],
              copyFile: [Function: copyFile],
              copyFileSync: [Function: copyFileSync],
              cp: [Function: cp],
              cpSync: [Function: cpSync],
              createReadStream: [Function: createReadStream],
              createWriteStream: [Function: createWriteStream],
              exists: [Function: exists],
              existsSync: [Function: existsSync],
              fchown: [Function: fchown],
              fchownSync: [Function: fchownSync],
              fchmod: [Function: fchmod],
              fchmodSync: [Function: fchmodSync],
              fdatasync: [Function: fdatasync],
              fdatasyncSync: [Function: fdatasyncSync],
              fstat: [Function: fstat],
              fstatSync: [Function: fstatSync],
              fsync: [Function: fsync],
              fsyncSync: [Function: fsyncSync],
              ftruncate: [Function: ftruncate],
              ftruncateSync: [Function: ftruncateSync],
              futimes: [Function: futimes],
              futimesSync: [Function: futimesSync],
              glob: [Function: glob],
              globSync: [Function: globSync],
              lchown: [Function: lchown],
              lchownSync: [Function: lchownSync],
              lchmod: undefined,
              lchmodSync: undefined,
              link: [Function: link],
              linkSync: [Function: linkSync],
              lstat: [Function: lstat],
              lstatSync: [Function: lstatSync],
              lutimes: [Function: lutimes],
              lutimesSync: [Function: lutimesSync],
              mkdir: [Function: mkdir],
              mkdirSync: [Function: mkdirSync],
              mkdtemp: [Function: mkdtemp],
              mkdtempSync: [Function: mkdtempSync],
              open: [Function: open],
              openSync: [Function: openSync],
              openAsBlob: [Function: openAsBlob],
              readdir: [Function: readdir],
              readdirSync: [Function: readdirSync],
              read: [Function: read],
              readSync: [Function: readSync],
              readv: [Function: readv],
              readvSync: [Function: readvSync],
              readFile: [Function: readFile],
              readFileSync: [Function: readFileSync],
              readlink: [Function: readlink],
              readlinkSync: [Function: readlinkSync],
              realpath: [Function: realpath] { native: [Function (anonymous)] },
              realpathSync: [Function: realpathSync] {
                native: [Function (anonymous)]
              },
              rename: [Function: rename],
              renameSync: [Function: renameSync],
              rm: [Function: rm],
              rmSync: [Function: rmSync],
              rmdir: [Function: rmdir],
              rmdirSync: [Function: rmdirSync],
              stat: [Function: stat],
              statfs: [Function: statfs],
              statSync: [Function: statSync],
              statfsSync: [Function: statfsSync],
              symlink: [Function: symlink],
              symlinkSync: [Function: symlinkSync],
              truncate: [Function: truncate],
              truncateSync: [Function: truncateSync],
              unwatchFile: [Function: unwatchFile],
              unlink: [Function: unlink],
              unlinkSync: [Function: unlinkSync],
              utimes: [Function: utimes],
              utimesSync: [Function: utimesSync],
              watch: [Function: watch],
              watchFile: [Function: watchFile],
              writeFile: [Function: writeFile],
              writeFileSync: [Function: writeFileSync],
              write: [Function: write],
              writeSync: [Function: writeSync],
              writev: [Function: writev],
              writevSync: [Function: writevSync],
              Dirent: [class Dirent],
              Stats: [Function: deprecated],
              ReadStream: [Getter/Setter],
              WriteStream: [Getter/Setter],
              FileReadStream: [Getter/Setter],
              FileWriteStream: [Getter/Setter],
              _toUnixTimestamp: [Function: toUnixTimestamp],
              Dir: [class Dir],
              opendir: [Function: opendir],
              opendirSync: [Function: opendirSync],
              F_OK: 0,
              R_OK: 4,
              W_OK: 2,
              X_OK: 1,
              constants: [Object: null prototype] {
                UV_FS_SYMLINK_DIR: 1,
                UV_FS_SYMLINK_JUNCTION: 2,
                O_RDONLY: 0,
                O_WRONLY: 1,
                O_RDWR: 2,
                UV_DIRENT_UNKNOWN: 0,
                UV_DIRENT_FILE: 1,
                UV_DIRENT_DIR: 2,
                UV_DIRENT_LINK: 3,
                UV_DIRENT_FIFO: 4,
                UV_DIRENT_SOCKET: 5,
                UV_DIRENT_CHAR: 6,
                UV_DIRENT_BLOCK: 7,
                S_IFMT: 61440,
                S_IFREG: 32768,
                S_IFDIR: 16384,
                S_IFCHR: 8192,
                S_IFIFO: 4096,
                S_IFLNK: 40960,
                O_CREAT: 256,
                O_EXCL: 1024,
                UV_FS_O_FILEMAP: 536870912,
                O_TRUNC: 512,
                O_APPEND: 8,
                S_IRUSR: 256,
                S_IWUSR: 128,
                F_OK: 0,
                R_OK: 4,
                W_OK: 2,
                X_OK: 1,
                UV_FS_COPYFILE_EXCL: 1,
                COPYFILE_EXCL: 1,
                UV_FS_COPYFILE_FICLONE: 2,
                COPYFILE_FICLONE: 2,
                UV_FS_COPYFILE_FICLONE_FORCE: 4,
                COPYFILE_FICLONE_FORCE: 4
              },
              promises: [Getter]
            },
            [Symbol(kIsPerformingIO)]: false,
            [Symbol(shapeMode)]: true,
            [Symbol(kCapture)]: false
          }
        },
        caption: 'Olá,\n' +
          '\n' +
          'Seu chamado foi atualizado com as seguintes informações:\n' +
          '\n' +
          '🔹 ID do Chamado: 4\n' +
          '🔹 Assunto: Erros na nova versao a ser olhado\n' +
          '🔹 Técnico Responsável: Renato\n' +
          '\n' +
          '4534543\n' +
          '\n' +
          'Caso tenha alguma dúvida ou precise de mais informações, estamos à disposição.\n' +
          '\n' +
          'Atenciosamente,\n' +
          '[Nome da Equipe/Suporte]'
      }
    }
  },
  level: 'error',
  timestamp: '2025-09-30T12:32:52.920Z'
}
{
  message: 'Erro em processamento do job SendMessageChamado (ID: 13)',
  error: 'Error: 400: Bad Request: IMAGE_PROCESS_FAILED',
  stack: 'Error: Error: 400: Bad Request: IMAGE_PROCESS_FAILED\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendMessageChamado.js:92:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-30T12:32:52.928Z'
}
{
  error: Error: Error: 400: Bad Request: IMAGE_PROCESS_FAILED
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:92:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendMessageChamado] Job 13 falhou. Erro: Error: 400: Bad Request: IMAGE_PROCESS_FAILED',
  timestamp: '2025-09-30T12:32:53.144Z'
}
{
  message: 'Error send message api',
  error: TelegramError: 400: Bad Request: IMAGE_PROCESS_FAILED
      at Telegram.callApi (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\telegraf\lib\core\network\client.js:315:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:52:25)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24) {
    response: {
      ok: false,
      error_code: 400,
      description: 'Bad Request: IMAGE_PROCESS_FAILED'
    },
    on: {
      method: 'sendPhoto',
      payload: {
        chat_id: '1015137420',
        photo: {
          source: ReadStream {
            fd: null,
            path: 'C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\chat bot new.json',
            flags: 'r',
            mode: 438,
            start: undefined,
            end: Infinity,
            pos: undefined,
            bytesRead: 86637,
            _events: {
              close: undefined,
              error: undefined,
              data: undefined,
              end: undefined,
              readable: undefined,
              [Symbol(kConstruct)]: undefined
            },
            _readableState: ReadableState {
              highWaterMark: 65536,
              buffer: [],
              bufferIndex: 0,
              length: 0,
              pipes: [],
              awaitDrainWriters: null,
              [Symbol(kState)]: 110626684
            },
            _maxListeners: undefined,
            _eventsCount: 0,
            [Symbol(kFs)]: {
              appendFile: [Function: appendFile],
              appendFileSync: [Function: appendFileSync],
              access: [Function: access],
              accessSync: [Function: accessSync],
              chown: [Function: chown],
              chownSync: [Function: chownSync],
              chmod: [Function: chmod],
              chmodSync: [Function: chmodSync],
              close: [Function: close],
              closeSync: [Function: closeSync],
              copyFile: [Function: copyFile],
              copyFileSync: [Function: copyFileSync],
              cp: [Function: cp],
              cpSync: [Function: cpSync],
              createReadStream: [Function: createReadStream],
              createWriteStream: [Function: createWriteStream],
              exists: [Function: exists],
              existsSync: [Function: existsSync],
              fchown: [Function: fchown],
              fchownSync: [Function: fchownSync],
              fchmod: [Function: fchmod],
              fchmodSync: [Function: fchmodSync],
              fdatasync: [Function: fdatasync],
              fdatasyncSync: [Function: fdatasyncSync],
              fstat: [Function: fstat],
              fstatSync: [Function: fstatSync],
              fsync: [Function: fsync],
              fsyncSync: [Function: fsyncSync],
              ftruncate: [Function: ftruncate],
              ftruncateSync: [Function: ftruncateSync],
              futimes: [Function: futimes],
              futimesSync: [Function: futimesSync],
              glob: [Function: glob],
              globSync: [Function: globSync],
              lchown: [Function: lchown],
              lchownSync: [Function: lchownSync],
              lchmod: undefined,
              lchmodSync: undefined,
              link: [Function: link],
              linkSync: [Function: linkSync],
              lstat: [Function: lstat],
              lstatSync: [Function: lstatSync],
              lutimes: [Function: lutimes],
              lutimesSync: [Function: lutimesSync],
              mkdir: [Function: mkdir],
              mkdirSync: [Function: mkdirSync],
              mkdtemp: [Function: mkdtemp],
              mkdtempSync: [Function: mkdtempSync],
              open: [Function: open],
              openSync: [Function: openSync],
              openAsBlob: [Function: openAsBlob],
              readdir: [Function: readdir],
              readdirSync: [Function: readdirSync],
              read: [Function: read],
              readSync: [Function: readSync],
              readv: [Function: readv],
              readvSync: [Function: readvSync],
              readFile: [Function: readFile],
              readFileSync: [Function: readFileSync],
              readlink: [Function: readlink],
              readlinkSync: [Function: readlinkSync],
              realpath: [Function: realpath] { native: [Function (anonymous)] },
              realpathSync: [Function: realpathSync] {
                native: [Function (anonymous)]
              },
              rename: [Function: rename],
              renameSync: [Function: renameSync],
              rm: [Function: rm],
              rmSync: [Function: rmSync],
              rmdir: [Function: rmdir],
              rmdirSync: [Function: rmdirSync],
              stat: [Function: stat],
              statfs: [Function: statfs],
              statSync: [Function: statSync],
              statfsSync: [Function: statfsSync],
              symlink: [Function: symlink],
              symlinkSync: [Function: symlinkSync],
              truncate: [Function: truncate],
              truncateSync: [Function: truncateSync],
              unwatchFile: [Function: unwatchFile],
              unlink: [Function: unlink],
              unlinkSync: [Function: unlinkSync],
              utimes: [Function: utimes],
              utimesSync: [Function: utimesSync],
              watch: [Function: watch],
              watchFile: [Function: watchFile],
              writeFile: [Function: writeFile],
              writeFileSync: [Function: writeFileSync],
              write: [Function: write],
              writeSync: [Function: writeSync],
              writev: [Function: writev],
              writevSync: [Function: writevSync],
              Dirent: [class Dirent],
              Stats: [Function: deprecated],
              ReadStream: [Getter/Setter],
              WriteStream: [Getter/Setter],
              FileReadStream: [Getter/Setter],
              FileWriteStream: [Getter/Setter],
              _toUnixTimestamp: [Function: toUnixTimestamp],
              Dir: [class Dir],
              opendir: [Function: opendir],
              opendirSync: [Function: opendirSync],
              F_OK: 0,
              R_OK: 4,
              W_OK: 2,
              X_OK: 1,
              constants: [Object: null prototype] {
                UV_FS_SYMLINK_DIR: 1,
                UV_FS_SYMLINK_JUNCTION: 2,
                O_RDONLY: 0,
                O_WRONLY: 1,
                O_RDWR: 2,
                UV_DIRENT_UNKNOWN: 0,
                UV_DIRENT_FILE: 1,
                UV_DIRENT_DIR: 2,
                UV_DIRENT_LINK: 3,
                UV_DIRENT_FIFO: 4,
                UV_DIRENT_SOCKET: 5,
                UV_DIRENT_CHAR: 6,
                UV_DIRENT_BLOCK: 7,
                S_IFMT: 61440,
                S_IFREG: 32768,
                S_IFDIR: 16384,
                S_IFCHR: 8192,
                S_IFIFO: 4096,
                S_IFLNK: 40960,
                O_CREAT: 256,
                O_EXCL: 1024,
                UV_FS_O_FILEMAP: 536870912,
                O_TRUNC: 512,
                O_APPEND: 8,
                S_IRUSR: 256,
                S_IWUSR: 128,
                F_OK: 0,
                R_OK: 4,
                W_OK: 2,
                X_OK: 1,
                UV_FS_COPYFILE_EXCL: 1,
                COPYFILE_EXCL: 1,
                UV_FS_COPYFILE_FICLONE: 2,
                COPYFILE_FICLONE: 2,
                UV_FS_COPYFILE_FICLONE_FORCE: 4,
                COPYFILE_FICLONE_FORCE: 4
              },
              promises: [Getter]
            },
            [Symbol(kIsPerformingIO)]: false,
            [Symbol(shapeMode)]: true,
            [Symbol(kCapture)]: false
          }
        },
        caption: 'Olá,\n' +
          '\n' +
          'Seu chamado foi atualizado com as seguintes informações:\n' +
          '\n' +
          '🔹 ID do Chamado: 4\n' +
          '🔹 Assunto: Erros na nova versao a ser olhado\n' +
          '🔹 Técnico Responsável: Renato\n' +
          '\n' +
          'telegram\n' +
          '\n' +
          'Caso tenha alguma dúvida ou precise de mais informações, estamos à disposição.\n' +
          '\n' +
          'Atenciosamente,\n' +
          '[Nome da Equipe/Suporte]'
      }
    }
  },
  level: 'error',
  timestamp: '2025-09-30T12:33:49.749Z'
}
{
  message: 'Erro em processamento do job SendMessageChamado (ID: 14)',
  error: 'Error: 400: Bad Request: IMAGE_PROCESS_FAILED',
  stack: 'Error: Error: 400: Bad Request: IMAGE_PROCESS_FAILED\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendMessageChamado.js:92:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-30T12:33:49.752Z'
}
{
  error: Error: Error: 400: Bad Request: IMAGE_PROCESS_FAILED
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:92:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendMessageChamado] Job 14 falhou. Erro: Error: 400: Bad Request: IMAGE_PROCESS_FAILED',
  timestamp: '2025-09-30T12:33:49.971Z'
}
{
  message: 'Error send message api',
  error: TelegramError: 400: Bad Request: IMAGE_PROCESS_FAILED
      at Telegram.callApi (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\telegraf\lib\core\network\client.js:315:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:52:25)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24) {
    response: {
      ok: false,
      error_code: 400,
      description: 'Bad Request: IMAGE_PROCESS_FAILED'
    },
    on: {
      method: 'sendPhoto',
      payload: {
        chat_id: '1015137420',
        photo: {
          source: 'C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\chat bot new.json',
          filename: undefined
        },
        caption: 'Olá,\n' +
          '\n' +
          'Seu chamado foi atualizado com as seguintes informações:\n' +
          '\n' +
          '🔹 ID do Chamado: 4\n' +
          '🔹 Assunto: Erros na nova versao a ser olhado\n' +
          '🔹 Técnico Responsável: Renato\n' +
          '\n' +
          'anexo\n' +
          '\n' +
          'Caso tenha alguma dúvida ou precise de mais informações, estamos à disposição.\n' +
          '\n' +
          'Atenciosamente,\n' +
          '[Nome da Equipe/Suporte]'
      }
    }
  },
  level: 'error',
  timestamp: '2025-09-30T12:35:37.772Z'
}
{
  message: 'Erro em processamento do job SendMessageChamado (ID: 15)',
  error: 'Error: 400: Bad Request: IMAGE_PROCESS_FAILED',
  stack: 'Error: Error: 400: Bad Request: IMAGE_PROCESS_FAILED\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendMessageChamado.js:90:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-30T12:35:37.775Z'
}
{
  error: Error: Error: 400: Bad Request: IMAGE_PROCESS_FAILED
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:90:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendMessageChamado] Job 15 falhou. Erro: Error: 400: Bad Request: IMAGE_PROCESS_FAILED',
  timestamp: '2025-09-30T12:35:37.996Z'
}
{
  message: 'Error send message api',
  error: TelegramError: 400: Bad Request: IMAGE_PROCESS_FAILED
      at Telegram.callApi (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\telegraf\lib\core\network\client.js:315:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:50:25)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24) {
    response: {
      ok: false,
      error_code: 400,
      description: 'Bad Request: IMAGE_PROCESS_FAILED'
    },
    on: {
      method: 'sendPhoto',
      payload: {
        chat_id: '1015137420',
        photo: {
          source: <Buffer 7b 0a 20 20 22 66 6c 6f 77 22 3a 20 7b 0a 20 20 20 20 22 6e 6f 64 65 4c 69 73 74 22 3a 20 5b 0a 20 20 20 20 20 20 7b 0a 20 20 20 20 20 20 20 20 22 69 ... 86587 more bytes>
        },
        caption: 'Olá,\n' +
          '\n' +
          'Seu chamado foi atualizado com as seguintes informações:\n' +
          '\n' +
          '🔹 ID do Chamado: 4\n' +
          '🔹 Assunto: Erros na nova versao a ser olhado\n' +
          '🔹 Técnico Responsável: Renato\n' +
          '\n' +
          '1212\n' +
          '\n' +
          'Caso tenha alguma dúvida ou precise de mais informações, estamos à disposição.\n' +
          '\n' +
          'Atenciosamente,\n' +
          '[Nome da Equipe/Suporte]'
      }
    }
  },
  level: 'error',
  timestamp: '2025-09-30T12:37:49.102Z'
}
{
  message: 'Erro em processamento do job SendMessageChamado (ID: 16)',
  error: 'Error: 400: Bad Request: IMAGE_PROCESS_FAILED',
  stack: 'Error: Error: 400: Bad Request: IMAGE_PROCESS_FAILED\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendMessageChamado.js:88:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-30T12:37:49.143Z'
}
{
  error: Error: Error: 400: Bad Request: IMAGE_PROCESS_FAILED
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:88:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendMessageChamado] Job 16 falhou. Erro: Error: 400: Bad Request: IMAGE_PROCESS_FAILED',
  timestamp: '2025-09-30T12:37:49.361Z'
}
{
  message: 'Error send message api',
  error: TelegramError: 400: Bad Request: IMAGE_PROCESS_FAILED
      at Telegram.callApi (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\telegraf\lib\core\network\client.js:315:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:51:25)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24) {
    response: {
      ok: false,
      error_code: 400,
      description: 'Bad Request: IMAGE_PROCESS_FAILED'
    },
    on: {
      method: 'sendPhoto',
      payload: {
        chat_id: '1015137420',
        photo: {
          source: 'C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\chat bot new.json'
        }
      }
    }
  },
  level: 'error',
  timestamp: '2025-09-30T12:42:10.241Z'
}
{
  message: 'Erro em processamento do job SendMessageChamado (ID: 19)',
  error: 'Error: 400: Bad Request: IMAGE_PROCESS_FAILED',
  stack: 'Error: Error: 400: Bad Request: IMAGE_PROCESS_FAILED\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendMessageChamado.js:91:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-30T12:42:10.245Z'
}
{
  error: Error: Error: 400: Bad Request: IMAGE_PROCESS_FAILED
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:91:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendMessageChamado] Job 19 falhou. Erro: Error: 400: Bad Request: IMAGE_PROCESS_FAILED',
  timestamp: '2025-09-30T12:42:10.471Z'
}
{
  message: 'Error send message api',
  error: TelegramError: 400: Bad Request: chat not found
      at Telegram.callApi (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\telegraf\lib\core\network\client.js:315:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:55:29)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24) {
    response: {
      ok: false,
      error_code: 400,
      description: 'Bad Request: chat not found'
    },
    on: {
      method: 'sendPhoto',
      payload: {
        chat_id: '0',
        photo: {
          source: 'C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\3Dias.png'
        },
        caption: 'Olá,\n' +
          '\n' +
          'Seu chamado foi atualizado com as seguintes informações:\n' +
          '\n' +
          '🔹 ID do Chamado: 4\n' +
          '🔹 Assunto: Erros na nova versao a ser olhado\n' +
          '🔹 Técnico Responsável: Renato\n' +
          '\n' +
          't4este\n' +
          '\n' +
          'Caso tenha alguma dúvida ou precise de mais informações, estamos à disposição.\n' +
          '\n' +
          'Atenciosamente,\n' +
          '[Nome da Equipe/Suporte]'
      }
    }
  },
  level: 'error',
  timestamp: '2025-09-30T13:12:23.244Z'
}
{
  message: 'Erro em processamento do job SendMessageChamado (ID: 26)',
  error: 'Error: 400: Bad Request: chat not found',
  stack: 'Error: Error: 400: Bad Request: chat not found\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendMessageChamado.js:113:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-30T13:12:23.246Z'
}
{
  error: Error: Error: 400: Bad Request: chat not found
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:113:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendMessageChamado] Job 26 falhou. Erro: Error: 400: Bad Request: chat not found',
  timestamp: '2025-09-30T13:12:23.468Z'
}
{
  message: 'Error send message api',
  error: TelegramError: 400: Bad Request: chat not found
      at Telegram.callApi (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\telegraf\lib\core\network\client.js:315:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:56:29)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24) {
    response: {
      ok: false,
      error_code: 400,
      description: 'Bad Request: chat not found'
    },
    on: {
      method: 'sendPhoto',
      payload: {
        chat_id: '0',
        photo: {
          source: 'C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\3Dias.png'
        },
        caption: 'Olá,\n' +
          '\n' +
          'Seu chamado foi atualizado com as seguintes informações:\n' +
          '\n' +
          '🔹 ID do Chamado: 4\n' +
          '🔹 Assunto: Erros na nova versao a ser olhado\n' +
          '🔹 Técnico Responsável: Renato\n' +
          '\n' +
          'teste\n' +
          '\n' +
          'Caso tenha alguma dúvida ou precise de mais informações, estamos à disposição.\n' +
          '\n' +
          'Atenciosamente,\n' +
          '[Nome da Equipe/Suporte]'
      }
    }
  },
  level: 'error',
  timestamp: '2025-09-30T13:13:33.507Z'
}
{
  message: 'Erro em processamento do job SendMessageChamado (ID: 27)',
  error: 'Error: 400: Bad Request: chat not found',
  stack: 'Error: Error: 400: Bad Request: chat not found\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendMessageChamado.js:114:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-30T13:13:33.509Z'
}
{
  error: Error: Error: 400: Bad Request: chat not found
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:114:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendMessageChamado] Job 27 falhou. Erro: Error: 400: Bad Request: chat not found',
  timestamp: '2025-09-30T13:13:33.733Z'
}
{
  message: 'Error send message api',
  error: {
    erro: true,
    to: '553185683733@c.us',
    text: 'Not an image, allowed formats png, jpeg and webp'
  },
  level: 'error',
  timestamp: '2025-09-30T13:15:42.671Z'
}
{
  message: 'Erro em processamento do job SendMessageChamado (ID: 29)',
  error: '[object Object]',
  stack: 'Error: [object Object]\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendMessageChamado.js:114:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-30T13:15:42.675Z'
}
{
  error: Error: [object Object]
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendMessageChamado.js:114:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendMessageChamado] Job 29 falhou. Erro: [object Object]',
  timestamp: '2025-09-30T13:15:42.894Z'
}
{
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\Olá,\n' +
    '\n' +
    'Seu chamado foi atualizado com as seguintes informações:\n' +
    '\n' +
    '🔹 ID do Chamado: 4\n' +
    '🔹 Assunto: Erros na nova versao a ser olhado\n' +
    '🔹 Técnico Responsável: Renato\n' +
    '\n' +
    'TESTESTES\n' +
    '\n' +
    'Caso tenha alguma dúvida ou precise de mais informações, estamos à disposição.\n' +
    '\n' +
    'Atenciosamente,\n' +
    '[Nome da Equipe\\Suporte]',
  level: 'error',
  message: "ENOENT: no such file or directory, open 'C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\Olá,\n" +
    '\n' +
    'Seu chamado foi atualizado com as seguintes informações:\n' +
    '\n' +
    '🔹 ID do Chamado: 4\n' +
    '🔹 Assunto: Erros na nova versao a ser olhado\n' +
    '🔹 Técnico Responsável: Renato\n' +
    '\n' +
    'TESTESTES\n' +
    '\n' +
    'Caso tenha alguma dúvida ou precise de mais informações, estamos à disposição.\n' +
    '\n' +
    'Atenciosamente,\n' +
    "[Nome da Equipe\\Suporte]'",
  stack: "Error: ENOENT: no such file or directory, open 'C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\Olá,\n" +
    '\n' +
    'Seu chamado foi atualizado com as seguintes informações:\n' +
    '\n' +
    '🔹 ID do Chamado: 4\n' +
    '🔹 Assunto: Erros na nova versao a ser olhado\n' +
    '🔹 Técnico Responsável: Renato\n' +
    '\n' +
    'TESTESTES\n' +
    '\n' +
    'Caso tenha alguma dúvida ou precise de mais informações, estamos à disposição.\n' +
    '\n' +
    'Atenciosamente,\n' +
    "[Nome da Equipe\\Suporte]'",
  timestamp: '2025-09-30T13:17:31.840Z'
}
{
  message: 'DEPURAÇÃO: Arquivo codificado não encontrado em C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\anexo. O teste não pode continuar.',
  level: 'error',
  timestamp: '2025-09-30T13:55:27.548Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 44)',
  error: 'DEPURAÇÃO: Arquivo codificado não encontrado em C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\anexo. O teste não pode continuar.',
  stack: 'Error: DEPURAÇÃO: Arquivo codificado não encontrado em C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\anexo. O teste não pode continuar.\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendEmail.js:37:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-30T13:55:27.550Z'
}
{
  error: Error: DEPURAÇÃO: Arquivo codificado não encontrado em C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\public\attachments\anexo. O teste não pode continuar.
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendEmail.js:37:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendEmail] Job 44 falhou. Erro: DEPURAÇÃO: Arquivo codificado não encontrado em C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\anexo. O teste não pode continuar.',
  timestamp: '2025-09-30T13:55:27.776Z'
}
{
  message: 'DEPURAÇÃO: Arquivo codificado não encontrado em C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\anexo. O teste não pode continuar.',
  level: 'error',
  timestamp: '2025-09-30T13:55:28.406Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 44)',
  error: 'DEPURAÇÃO: Arquivo codificado não encontrado em C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\anexo. O teste não pode continuar.',
  stack: 'Error: DEPURAÇÃO: Arquivo codificado não encontrado em C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\anexo. O teste não pode continuar.\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendEmail.js:37:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-30T13:55:28.407Z'
}
{
  error: Error: DEPURAÇÃO: Arquivo codificado não encontrado em C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\public\attachments\anexo. O teste não pode continuar.
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendEmail.js:37:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendEmail] Job 44 falhou. Erro: DEPURAÇÃO: Arquivo codificado não encontrado em C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\anexo. O teste não pode continuar.',
  timestamp: '2025-09-30T13:55:28.628Z'
}
{
  message: 'DEPURAÇÃO: Arquivo codificado não encontrado em C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\anexo. O teste não pode continuar.',
  level: 'error',
  timestamp: '2025-09-30T13:55:29.103Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 44)',
  error: 'DEPURAÇÃO: Arquivo codificado não encontrado em C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\anexo. O teste não pode continuar.',
  stack: 'Error: DEPURAÇÃO: Arquivo codificado não encontrado em C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\anexo. O teste não pode continuar.\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendEmail.js:37:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-30T13:55:29.104Z'
}
{
  error: Error: DEPURAÇÃO: Arquivo codificado não encontrado em C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\public\attachments\anexo. O teste não pode continuar.
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendEmail.js:37:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendEmail] Job 44 falhou. Erro: DEPURAÇÃO: Arquivo codificado não encontrado em C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\anexo. O teste não pode continuar.',
  timestamp: '2025-09-30T13:55:29.328Z'
}
{
  message: 'DEPURAÇÃO: Arquivo codificado não encontrado em C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\anexo. O teste não pode continuar.',
  level: 'error',
  timestamp: '2025-09-30T13:57:06.340Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 45)',
  error: 'DEPURAÇÃO: Arquivo codificado não encontrado em C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\anexo. O teste não pode continuar.',
  stack: 'Error: DEPURAÇÃO: Arquivo codificado não encontrado em C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\anexo. O teste não pode continuar.\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendEmail.js:37:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-30T13:57:06.343Z'
}
{
  error: Error: DEPURAÇÃO: Arquivo codificado não encontrado em C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\public\attachments\anexo. O teste não pode continuar.
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendEmail.js:37:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendEmail] Job 45 falhou. Erro: DEPURAÇÃO: Arquivo codificado não encontrado em C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\anexo. O teste não pode continuar.',
  timestamp: '2025-09-30T13:57:06.564Z'
}
{
  message: 'DEPURAÇÃO: Arquivo codificado não encontrado em C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\anexo. O teste não pode continuar.',
  level: 'error',
  timestamp: '2025-09-30T13:57:07.224Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 45)',
  error: 'DEPURAÇÃO: Arquivo codificado não encontrado em C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\anexo. O teste não pode continuar.',
  stack: 'Error: DEPURAÇÃO: Arquivo codificado não encontrado em C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\anexo. O teste não pode continuar.\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendEmail.js:37:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-30T13:57:07.225Z'
}
{
  error: Error: DEPURAÇÃO: Arquivo codificado não encontrado em C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\public\attachments\anexo. O teste não pode continuar.
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendEmail.js:37:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendEmail] Job 45 falhou. Erro: DEPURAÇÃO: Arquivo codificado não encontrado em C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\anexo. O teste não pode continuar.',
  timestamp: '2025-09-30T13:57:07.444Z'
}
{
  message: 'DEPURAÇÃO: Arquivo codificado não encontrado em C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\anexo. O teste não pode continuar.',
  level: 'error',
  timestamp: '2025-09-30T13:57:07.886Z'
}
{
  message: 'Erro em processamento do job SendEmail (ID: 45)',
  error: 'DEPURAÇÃO: Arquivo codificado não encontrado em C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\anexo. O teste não pode continuar.',
  stack: 'Error: DEPURAÇÃO: Arquivo codificado não encontrado em C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\anexo. O teste não pode continuar.\n' +
    '    at handle (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\jobs\\SendEmail.js:37:19)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async bullmq_1.Worker.connection [as processFn] (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\dist\\lib\\Queue.js:154:32)\n' +
    '    at async C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:498:32\n' +
    '    at async Worker.retryIfFailed (C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\node_modules\\bullmq\\dist\\cjs\\classes\\worker.js:776:24)',
  level: 'error',
  timestamp: '2025-09-30T13:57:07.887Z'
}
{
  error: Error: DEPURAÇÃO: Arquivo codificado não encontrado em C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\public\attachments\anexo. O teste não pode continuar.
      at handle (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\jobs\SendEmail.js:37:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async bullmq_1.Worker.connection [as processFn] (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\dist\lib\Queue.js:154:32)
      at async C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:498:32
      at async Worker.retryIfFailed (C:\Users\suporte2\Documents\Programacao\Nodejs\Fastify\node_modules\bullmq\dist\cjs\classes\worker.js:776:24),
  level: 'error',
  message: '[Worker SendEmail] Job 45 falhou. Erro: DEPURAÇÃO: Arquivo codificado não encontrado em C:\\Users\\suporte2\\Documents\\Programacao\\Nodejs\\Fastify\\public\\attachments\\anexo. O teste não pode continuar.',
  timestamp: '2025-09-30T13:57:08.110Z'
}
{
  message: 'Unhandled Rejection: Error: Falha ao enviar e-mail',
  level: 'error',
  timestamp: '2025-09-30T14:00:08.899Z'
}
{
  message: 'Unhandled Rejection: Error: Falha ao enviar e-mail',
  level: 'error',
  timestamp: '2025-09-30T14:05:05.898Z'
}
{
  message: 'Unhandled Rejection: Error: Falha ao enviar e-mail',
  level: 'error',
  timestamp: '2025-09-30T14:06:43.503Z'
}
